import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Clock3, Save, Settings2, Store, ToggleLeft, Bell, ShieldCheck } from "lucide-react";
import { auth, db } from "../firebaseConfig";
import { doc, getDoc, setDoc, serverTimestamp } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const DEFAULT_HOURS = DAYS.reduce((a, d) => ({ ...a, [d]: { open: "09:00", close: "22:00", enabled: true } }), {});
const DEFAULTS = { restaurantName: "Eatalio", logoURL: "", phone: "", email: "", address: "", currency: "MVR", taxPercent: 8, restaurantStatus: "open", onlineOrderingEnabled: true, dineInEnabled: true, takeawayEnabled: true, deliveryEnabled: true, guestOrderingEnabled: true, accountsEnabled: true, statusTrackingEnabled: true, addToActiveDineInSession: true, notificationsEnabled: true, maintenanceMode: false, openingHours: DEFAULT_HOURS };
const normalize = s => ({ ...DEFAULTS, ...(s || {}), taxPercent: 8, openingHours: DAYS.reduce((a,d) => ({ ...a, [d]: { ...DEFAULT_HOURS[d], ...(s?.openingHours?.[d] || {}) } }), {}) });

function Field({ label, value, onChange, type = "text", placeholder, readOnly = false }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span><input type={type} value={value ?? ""} onChange={e => onChange(e.target.value)} placeholder={placeholder} readOnly={readOnly} className={`w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-100 ${readOnly ? "cursor-not-allowed bg-slate-50 text-slate-600" : ""}`} /></label>; }
function Toggle({ label, description, checked, onChange }) { return <button type="button" onClick={() => onChange(!checked)} className={`flex w-full items-center justify-between gap-4 rounded-2xl border p-4 text-left transition hover:border-slate-300 ${checked ? "border-slate-300 bg-slate-50" : "border-slate-200 bg-white"}`}><div><div className="font-semibold text-slate-900">{label}</div>{description && <div className="mt-0.5 text-xs leading-5 text-slate-500">{description}</div>}</div><span className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked ? "bg-slate-900" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`} /></span></button>; }

export default function AdminSettings() {
  const navigate = useNavigate(); const [settings, setSettings] = useState(DEFAULTS); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const unsub = onAuthStateChanged(auth, async user => { if (!user) return navigate("/AdminLogin"); try { const staff = await getDoc(doc(db, "staff", user.uid)); if (!staff.exists() || String(staff.data()?.role || "").toLowerCase() !== "admin") return navigate("/"); const snap = await getDoc(doc(db, "settings", "app")); const current = snap.exists() ? snap.data() : {}; setSettings(normalize(current)); if (Number(current.taxPercent ?? current.taxRate ?? 8) !== 8) await setDoc(doc(db, "settings", "app"), { taxPercent: 8, updatedAt: serverTimestamp() }, { merge: true }); } catch { navigate("/"); } finally { setLoading(false); } }); return () => unsub(); }, [navigate]);
  const update = (k,v) => setSettings(p => ({ ...p, [k]: v }));
  const updateHour = (day,k,v) => setSettings(p => ({ ...p, openingHours: { ...p.openingHours, [day]: { ...p.openingHours[day], [k]: v } } }));
  const save = async e => { e.preventDefault(); if (!settings.restaurantName.trim()) return setMessage("Restaurant name is required."); if (![settings.dineInEnabled,settings.takeawayEnabled,settings.deliveryEnabled].some(Boolean)) return setMessage("Enable at least one ordering method."); setSaving(true); setMessage(""); try { await setDoc(doc(db,"settings","app"),{...settings,taxPercent:8,updatedAt:serverTimestamp()},{merge:true}); setSettings(p=>({...p,taxPercent:8})); setMessage("Settings saved successfully."); } catch(err) { setMessage(err.message || "Could not save settings."); } finally { setSaving(false); } };
  if (loading) return <div className="min-h-screen bg-slate-50 p-8 text-sm text-slate-500">Loading settings…</div>;
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><button type="button" onClick={() => navigate("/admin/dashboard")} className="flex items-center gap-2 text-sm font-medium text-slate-600"><ArrowLeft size={18}/> Admin</button><div className="flex items-center gap-2"><Settings2 size={18}/><span className="font-bold">Settings</span></div><button type="button" onClick={save} disabled={saving} className="flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Save size={16}/>{saving ? "Saving…" : "Save"}</button></div></header><form onSubmit={save} className="mx-auto max-w-5xl space-y-6 px-5 py-7">{message && <div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium">{message}</div>}
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><Store size={20}/><div><h2 className="font-bold">Restaurant information</h2><p className="text-xs text-slate-500">Details shown to customers.</p></div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Restaurant name" value={settings.restaurantName} onChange={v=>update("restaurantName",v)}/><Field label="Logo URL" value={settings.logoURL} onChange={v=>update("logoURL",v)} placeholder="https://…"/><Field label="Phone" value={settings.phone} onChange={v=>update("phone",v)}/><Field label="Email" value={settings.email} onChange={v=>update("email",v)} type="email"/><div className="md:col-span-2"><Field label="Address" value={settings.address} onChange={v=>update("address",v)}/></div></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><Clock3 size={20}/><div><h2 className="font-bold">Opening hours</h2><p className="text-xs text-slate-500">Set the hours displayed to customers.</p></div></div><div className="space-y-3">{DAYS.map(day=><div key={day} className="grid items-center gap-3 rounded-2xl bg-slate-50 p-3 sm:grid-cols-[1fr_auto_auto_auto]"><div className="text-sm font-medium">{day}</div><label className="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={settings.openingHours[day].enabled} onChange={e=>updateHour(day,"enabled",e.target.checked)}/> Open</label><input type="time" disabled={!settings.openingHours[day].enabled} value={settings.openingHours[day].open} onChange={e=>updateHour(day,"open",e.target.value)} className="rounded-lg border border-slate-200 px-2.5 py-2 text-sm"/><input type="time" disabled={!settings.openingHours[day].enabled} value={settings.openingHours[day].close} onChange={e=>updateHour(day,"close",e.target.value)} className="rounded-lg border border-slate-200 px-2.5 py-2 text-sm"/></div>)}</div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><ToggleLeft size={20}/><div><h2 className="font-bold">Ordering</h2><p className="text-xs text-slate-500">Control available ordering channels.</p></div></div><div className="grid gap-3 md:grid-cols-2"><Toggle label="Restaurant open" description="Customers see the restaurant as open." checked={settings.restaurantStatus === "open"} onChange={v=>update("restaurantStatus",v?"open":"closed")}/><Toggle label="Online ordering" description="Master switch for placing new orders." checked={settings.onlineOrderingEnabled} onChange={v=>update("onlineOrderingEnabled",v)}/><Toggle label="Dine-in" checked={settings.dineInEnabled} onChange={v=>update("dineInEnabled",v)}/><Toggle label="Takeaway" checked={settings.takeawayEnabled} onChange={v=>update("takeawayEnabled",v)}/><Toggle label="Delivery" description="Delivery is arranged manually by the restaurant." checked={settings.deliveryEnabled} onChange={v=>update("deliveryEnabled",v)}/></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-1 font-bold">Tax & checkout</h2><p className="mb-5 text-xs text-slate-500">All menu prices are GST-inclusive. GST is fixed at 8% and is not added on top of menu prices.</p><div className="grid gap-4 md:grid-cols-2"><Field label="GST / tax (%)" value={8} onChange={()=>{}} type="number" readOnly/><Field label="Currency" value={settings.currency} onChange={v=>update("currency",v)}/></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><Bell size={20}/><div><h2 className="font-bold">Customer experience</h2><p className="text-xs text-slate-500">Global customer-order behavior.</p></div></div><div className="grid gap-3 md:grid-cols-2"><Toggle label="Guest ordering" description="Allow ordering without an account." checked={settings.guestOrderingEnabled} onChange={v=>update("guestOrderingEnabled",v)}/><Toggle label="Customer accounts" description="Keep optional sign-in support available." checked={settings.accountsEnabled} onChange={v=>update("accountsEnabled",v)}/><Toggle label="Order status tracking" checked={settings.statusTrackingEnabled} onChange={v=>update("statusTrackingEnabled",v)}/><Toggle label="Add to active dine-in session" description="Allow additional orders to join the current table session." checked={settings.addToActiveDineInSession} onChange={v=>update("addToActiveDineInSession",v)}/><Toggle label="Notifications" checked={settings.notificationsEnabled} onChange={v=>update("notificationsEnabled",v)}/></div></section>
  <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-start gap-3"><ShieldCheck size={20}/><div className="flex-1"><h2 className="font-bold">Maintenance mode</h2><p className="mt-1 text-xs leading-5 text-slate-600">Temporarily stop customer ordering while keeping admin access.</p><div className="mt-4 max-w-xl"><Toggle label="Maintenance mode" description="Customer ordering should be unavailable while enabled." checked={settings.maintenanceMode} onChange={v=>update("maintenanceMode",v)}/></div></div></div></section>
  <div className="flex justify-end pb-8"><button type="submit" disabled={saving} className="flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-3 font-semibold text-white disabled:opacity-60"><Save size={17}/>{saving?"Saving…":"Save settings"}</button></div></form></div>;
}
