import React, { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, MapPin, PackageCheck, ShoppingBag } from "lucide-react";
import { doc, onSnapshot } from "firebase/firestore";
import { useNavigate, useParams } from "react-router-dom";
import { db } from "../firebaseConfig";

function money(v) { return `MVR ${Number(v || 0).toFixed(0)}`; }
function typeLabel(t) { return t === "dine-in" ? "Dine In" : t === "delivery" ? "Delivery" : "Takeaway"; }
function statusLabel(order) { return order?.orderStatus || (order?.status === "Pending" ? "Received" : order?.status) || "Received"; }
function statusIcon(status) { if (status === "Completed") return <CheckCircle2 size={20}/>; if (status === "Preparing") return <Clock3 size={20}/>; if (status === "Ready" || status === "Ready for Pickup" || status === "Out for Delivery") return <PackageCheck size={20}/>; return <ShoppingBag size={20}/>; }

export default function CustomerOrder() {
  const { id } = useParams(); const navigate = useNavigate(); const [order, setOrder] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => onSnapshot(doc(db, "orders", id), (snap) => { setOrder(snap.exists() ? { id: snap.id, ...snap.data() } : null); setLoading(false); }, () => setLoading(false)), [id]);
  if (loading) return <div className="min-h-screen bg-[#fafaf9] p-8 text-center text-sm text-slate-500">Loading order…</div>;
  if (!order) return <div className="min-h-screen bg-[#fafaf9] p-8 text-center"><p className="font-semibold">Order not found</p><button onClick={() => navigate("/orders")} className="mt-4 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">My Orders</button></div>;
  const status = statusLabel(order); const labels = order.orderType === "takeaway" ? ["Received","Accepted","Preparing","Ready for Pickup","Completed"] : order.orderType === "delivery" ? ["Received","Accepted","Preparing","Ready","Out for Delivery","Completed"] : ["Received","Accepted","Preparing","Ready","Completed"]; const current = Math.max(0, labels.indexOf(status));
  return <div className="min-h-screen bg-[#fafaf9] pb-10 text-slate-950"><header className="border-b border-slate-200/70"><div className="mx-auto flex h-16 max-w-3xl items-center px-5 sm:px-8"><button onClick={() => navigate("/orders")} className="mr-3 rounded-full p-2 hover:bg-slate-100"><ArrowLeft size={20}/></button><h1 className="text-lg font-semibold">Order Summary</h1></div></header><main className="mx-auto max-w-3xl space-y-5 px-5 py-7 sm:px-8">
    <section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs text-white/55">Order #{order.orderNumber || order.id.slice(-6).toUpperCase()}</p><div className="mt-3 flex items-center gap-2 text-lg font-semibold">{statusIcon(status)}{status}</div><p className="mt-2 text-sm text-white/65">{typeLabel(order.orderType)}{order.tableNumber ? ` · Table ${order.tableNumber}` : ""}</p></section>
    <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/70"><h2 className="font-semibold">Order progress</h2><div className="mt-5 space-y-4">{labels.map((label,i) => <div key={label} className="flex items-center gap-3"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${i <= current ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-400"}`}>{i < current ? <CheckCircle2 size={16}/> : <span className="text-xs font-bold">{i+1}</span>}</div><span className={`text-sm ${i === current ? "font-semibold" : i < current ? "text-slate-600" : "text-slate-400"}`}>{label}</span></div>)}</div></section>
    {order.orderType === "delivery" && order.delivery && <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/70"><h2 className="flex items-center gap-2 font-semibold"><MapPin size={18}/> Delivery details</h2><p className="mt-4 text-sm font-medium">{order.delivery.area}</p><p className="mt-1 text-sm text-slate-500">{order.delivery.address}</p>{order.delivery.landmark && <p className="mt-2 text-xs text-slate-400">Landmark: {order.delivery.landmark}</p>}</section>}
    <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/70"><h2 className="font-semibold">Your items</h2><div className="mt-4 divide-y divide-slate-100">{(order.items || []).map((item,i) => <div key={`${item.id}-${i}`} className="flex items-center gap-3 py-3 first:pt-0"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold">{item.quantity}×</div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.name}</p></div><span className="text-sm font-semibold">{money(Number(item.price || 0) * Number(item.quantity || 0))}</span></div>)}</div>{order.specialInstructions && <div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><b className="text-slate-700">Note:</b> {order.specialInstructions}</div>}<div className="mt-4 space-y-2 border-t border-slate-100 pt-4 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><span>{money(order.subtotal)}</span></div>{order.deliveryFee != null && order.orderType === "delivery" && <div className="flex justify-between"><span className="text-slate-500">Delivery</span><span>{Number(order.deliveryFee) === 0 ? "Free" : money(order.deliveryFee)}</span></div>}<div className="flex justify-between"><span className="text-slate-500">GST ({order.taxPercent ?? 8}%)</span><span>{money(order.tax)}</span></div><div className="flex justify-between border-t border-slate-100 pt-3 font-semibold"><span>Total</span><span>{money(order.total)}</span></div></div></section>
    {status === "Completed" && <button onClick={() => navigate("/menu")} className="h-12 w-full rounded-2xl bg-slate-950 text-sm font-semibold text-white">Order Again</button>}
  </main></div>;
}
