import React, { useEffect, useMemo, useState } from "react";
import { Check, CreditCard, Eye, LogOut, MapPin, Phone, Search, UserRound, X, Utensils } from "lucide-react";
import { collection, doc, getDoc, onSnapshot, serverTimestamp, updateDoc, addDoc } from "firebase/firestore";
import { signOut } from "firebase/auth";
import { useNavigate } from "react-router-dom";
import { auth, db } from "../firebaseConfig";

const normalize=o=>o.orderStatus||(o.status==="Pending"?"Received":o.status)||"Received";
const stages=t=>t==="takeaway"?["Received","Accepted","Preparing","Ready for Pickup","Completed"]:t==="delivery"?["Received","Accepted","Preparing","Ready","Out for Delivery","Completed"]:["Received","Accepted","Preparing","Ready","Completed"];
const money=v=>`MVR ${Number(v||0).toFixed(2)}`;
const typeName=t=>t==="dine-in"?"Dine In":t==="delivery"?"Delivery":"Takeaway";
const isOpen=o=>!["Completed","Cancelled","Canceled"].includes(normalize(o));
const nextStage=o=>{const a=stages(o.orderType),i=a.indexOf(normalize(o));return a[i+1]||null};

export default function StaffOrders(){
 const navigate=useNavigate();const [orders,setOrders]=useState([]);const [filter,setFilter]=useState("active");const [search,setSearch]=useState("");const [selected,setSelected]=useState(null);const [authorized,setAuthorized]=useState(false);const [checking,setChecking]=useState(true);
 useEffect(()=>auth.onAuthStateChanged(async user=>{if(!user){navigate('/StaffLogin');return;}const snap=await getDoc(doc(db,'staff',user.uid));const d=snap.data()||{};const role=String(d.role||'').toLowerCase();if(role==='staff'||role==='admin')setAuthorized(true);else navigate('/');setChecking(false)}),[navigate]);
 useEffect(()=>onSnapshot(collection(db,'orders'),snap=>setOrders(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||b.timestamp?.seconds||0)-(a.createdAt?.seconds||a.timestamp?.seconds||0)))),[]);
 const sessions=useMemo(()=>{const m={};orders.filter(o=>o.orderType==='dine-in'&&o.tableSessionId).forEach(o=>{const id=o.tableSessionId;if(!m[id])m[id]={id,tableId:o.tableId,tableNumber:o.tableNumber||'—',orders:[],total:0};m[id].orders.push(o);m[id].total+=Number(o.total||0)});return Object.values(m).sort((a,b)=>(b.orders[0]?.createdAt?.seconds||0)-(a.orders[0]?.createdAt?.seconds||0));},[orders]);
 const filtered=useMemo(()=>orders.filter(o=>{const s=normalize(o),f=filter==='active'?isOpen(o):filter==='completed'?s==='Completed':filter==='cancelled'?["Cancelled","Canceled"].includes(s):true,q=search.toLowerCase();return f&&(!q||`${o.id} ${o.orderNumber||''} ${o.customerName||''} ${o.customerPhone||''} ${o.tableNumber||''} ${o.tableSessionId||''}`.toLowerCase().includes(q));}),[orders,filter,search]);
 const update=async(o,status)=>{if(!status||status===normalize(o))return;const fromStatus=normalize(o);await updateDoc(doc(db,'orders',o.id),{orderStatus:status,status,updatedAt:serverTimestamp(),updatedBy:auth.currentUser?.uid||'staff'});await addDoc(collection(db,'activityLogs'),{action:'order_status_changed',orderId:o.id,orderNumber:o.orderNumber||'',fromStatus,toStatus:status,actorId:auth.currentUser?.uid||'staff',actorRole:'staff',createdAt:serverTimestamp()});};
 const logout=async()=>{await signOut(auth);navigate('/StaffLogin')};
 if(checking||!authorized)return <div className="min-h-screen bg-[#f7f7f5] p-8 text-center text-sm text-slate-500">Loading staff workspace…</div>;
 return <div className="min-h-screen bg-[#f7f7f5] text-slate-950"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><div><h1 className="text-lg font-bold">Orders</h1><p className="text-xs text-slate-400">Staff workspace</p></div><div className="flex items-center gap-2"><button onClick={()=>navigate('/kitchen')} className="rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-100">Kitchen</button><button onClick={logout} className="rounded-xl p-2 hover:bg-slate-100"><LogOut size={18}/></button></div></div></header><main className="mx-auto max-w-7xl px-5 py-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-slate-400">{filtered.length} order{filtered.length===1?'':'s'}</p><h2 className="text-3xl font-semibold tracking-tight">Keep orders moving.</h2></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search orders" className="h-11 w-full rounded-xl bg-white pl-10 pr-3 text-sm outline-none ring-1 ring-slate-200"/></div></div><section className="mt-6"><div className="mb-3"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Dine-in table sessions</p><h3 className="text-xl font-bold">Open table activity</h3></div><div className="grid gap-3 lg:grid-cols-2">{sessions.filter(s=>s.orders.some(isOpen)).map(s=><SessionCard key={s.id} session={s}/>)}</div>{!sessions.some(s=>s.orders.some(isOpen))&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-400">No open dine-in sessions.</div>}</section><div className="mt-8 flex gap-2 overflow-x-auto">{[['active','Active'],['completed','Completed'],['cancelled','Cancelled'],['all','All']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-full px-4 py-2 text-sm font-semibold ${filter===v?'bg-slate-950 text-white':'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{l}</button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(o=><OrderCard key={o.id} order={o} onView={()=>setSelected(o)} onNext={()=>{const n=nextStage(o);if(n)update(o,n)}} onCancel={()=>update(o,'Cancelled')}/>)}{!filtered.length&&<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">No orders here.</div>}</div></main>{selected&&<OrderModal order={selected} close={()=>setSelected(null)} onUpdate={s=>{update(selected,s);setSelected({...selected,orderStatus:s,status:s})}}/>}</div>;
}
function SessionCard({session}){return <article className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Current session</p><h4 className="mt-1 text-xl font-bold">Table {session.tableNumber}</h4><p className="mt-1 text-xs text-slate-400">Session {session.id}</p></div><Utensils size={20}/></div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4"><div><p className="text-xs text-slate-400">{session.orders.length} order rounds</p><p className="text-lg font-bold">{money(session.total)}</p></div><span className="rounded-xl bg-white/10 px-4 py-2.5 text-xs font-semibold text-slate-300">Close from Admin</span></div><div className="mt-4 space-y-2">{session.orders.map(o=><div key={o.id} className="flex items-center justify-between rounded-xl bg-white/10 px-3 py-2 text-sm"><span>#{o.orderNumber||o.id.slice(-6).toUpperCase()}</span><span className="text-slate-300">{normalize(o)} · {money(o.total)}</span></div>)}</div></article>}
function OrderCard({order,onView,onNext,onCancel}){const status=normalize(order),n=nextStage(order),count=(order.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0);return <article className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/70"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold text-slate-400">#{order.orderNumber||order.id.slice(-6).toUpperCase()}</p><h3 className="mt-1 font-bold">{order.orderType==='dine-in'?`Table ${order.tableNumber||'—'}`:typeName(order.orderType)}</h3><p className="mt-1 text-xs text-slate-400">{count} item{count===1?'':'s'} · {money(order.total)}</p></div><span className="h-fit rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{status}</span></div>{order.customerName&&<div className="mt-4 text-sm"><p className="font-medium">{order.customerName}</p>{order.customerPhone&&<p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Phone size={13}/>{order.customerPhone}</p>}</div>}<div className="mt-4 space-y-1 border-t border-slate-100 pt-3">{(order.items||[]).slice(0,3).map((i,n)=><p key={n} className="text-sm"><b>{i.quantity}×</b> {i.name}</p>)}</div>{order.specialInstructions&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b>Note:</b> {order.specialInstructions}</p>}<div className="mt-4 flex gap-2"><button onClick={onView} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-100 text-sm font-semibold"><Eye size={16}/> Details</button>{n&&<button onClick={onNext} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-semibold text-white"><Check size={16}/> {n}</button>}</div>{!['Completed','Cancelled','Canceled'].includes(status)&&<button onClick={onCancel} className="mt-2 w-full py-1 text-xs font-medium text-slate-400 hover:text-red-600">Cancel order</button>}</article>}
function OrderModal({order,close,onUpdate}){const payment=order.payment||{};return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/45 sm:items-center sm:p-6" onClick={close}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-t-3xl bg-white p-6 sm:rounded-3xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs text-slate-400">#{order.orderNumber||order.id.slice(-6).toUpperCase()}</p><h2 className="mt-1 text-2xl font-bold">{typeName(order.orderType)}</h2>{order.tableSessionId&&<p className="mt-1 text-xs text-slate-400">Table {order.tableNumber} · Session {order.tableSessionId}</p>}</div><button onClick={close} className="rounded-full p-2 hover:bg-slate-100"><X size={19}/></button></div><div className="mt-5 space-y-4">{order.customerName&&<div><p className="flex items-center gap-2 text-sm font-semibold"><UserRound size={16}/> {order.customerName}</p><p className="mt-1 text-sm text-slate-500">{order.customerPhone}</p></div>}{order.delivery&&<div className="rounded-xl bg-slate-50 p-4 text-sm"><p className="flex items-center gap-2 font-semibold"><MapPin size={16}/> {order.delivery.area}</p><p className="mt-1 text-slate-600">{order.delivery.address}</p></div>}<div>{(order.items||[]).map((i,n)=><div key={n} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span><b>{i.quantity}×</b> {i.name}</span><span>{money(Number(i.price||0)*Number(i.quantity||0))}</span></div>)}</div>{order.specialInstructions&&<div className="rounded-xl bg-slate-50 p-3 text-sm"><b>Special instructions</b><p className="mt-1 text-slate-600">{order.specialInstructions}</p></div>}<div className="rounded-xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><CreditCard size={16}/> Payment</p><p className="mt-2 text-sm">Method: <b>{payment.method==='bank-transfer'?'Bank Transfer':payment.method==='none'?'Not required':'Cash'}</b></p>{payment.status&&<p className="mt-1 text-xs text-slate-500">Status: {payment.status}</p>}{payment.slipURL&&<a href={payment.slipURL} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-semibold underline">View payment slip</a>}</div><div className="flex justify-between border-t border-slate-200 pt-4 font-semibold"><span>Total</span><span>{money(order.total)}</span></div><div className="grid grid-cols-2 gap-2">{stages(order.orderType).map(s=><button key={s} onClick={()=>onUpdate(s)} className={`rounded-xl border px-2 py-2 text-xs font-semibold ${normalize(order)===s?'bg-slate-950 text-white':'border-slate-200'}`}>{s}</button>)}</div></div></div></div>}
